version: '3.7'
services:
  mysql:
    build: ./database
    restart: always
    ports:
      - "3306:3306"

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    environment:
      NODE_ENV: dev
      DEBUG: "true"
      WAIT_HOSTS: mysql:3306
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: eisenhowerMatrix
      MYSQL_DATABASE: eisenhower
      MYSQL_USER: root
      JWT_KEY: 2lfAtoo9hG
    ports:
      - "3000:3000"
    depends_on:
      - mysql
